spring:
  profiles:
    active: production
  security:
    basic:
      enabled: true
    user:
      password: trycatch
      name: trycatch
  application:
    name: service-discovery-peer3
server:
  port: 8103

eureka:
  instance:
    hostname: peer3
    appname: peer3
    ip-address: 192.168.1.58
    instance-id: ${eureka.instance.ip-address}:${server.port}
    prefer-ip-address: true
    statusPageUrl: https://${eureka.instance.ip-address}:${server.port}/info
    healthCheckUrl: https://${eureka.instance.ip-address}:${server.port}/health
    homePageUrl: https://${eureka.instance.ip-address}:${server.port}
    lease-expiration-duration-in-seconds: 90
  client:
    healthcheck:
      enabled: true
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://trycatch:trycatch@127.0.0.1:8101/eureka/,http://trycatch:trycatch@127.0.0.1:8103/eureka/,http://trycatch:trycatch@127.0.0.1:8888/eureka/
  server:
    waitTimeInMsWhenSyncEmpty: 0