server:
  port: 8004
instance:
  hostname: 192.168.1.58

spring:
  application:
      name: service-client
  datasource:
    txdiag:
      jdbc-url: jdbc:mysql://localhost:3306/txdiag?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password:
      driver-class-name: com.mysql.jdbc.Driver
    txhims:
      jdbc-url: jdbc:mysql://localhost:3306/txhims?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password:
      driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database: mysql
    format: true
    show-sql: true
    hibernate:
      txdiag:
        persistence-unit: txdiagUnit
      txhims:
        persistence-unit: txhimsUnit
      dialect: org.hibernate.dialect.MySQL5Dialect
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
logging:
  config: classpath:logback-boot.xml
  file: log/myapplication.log

eureka:
  client:
     serviceUrl:
        defaultZone: http://trycatch:trycatch@192.168.1.58:8101/eureka/,http://trycatch:trycatch@192.168.1.58:8103/eureka/,http://trycatch:trycatch@192.168.1.58:8888/eureka/